### ISSUE TITLE
debug with vscode --document is not defined

### ISSUE THREAD

**Issue by momu-smartcoach** [artf/grapesjs#1110]
i debug the code with vscode ,follow the Course（https://medium.com/@drcallaway/debugging-es6-in-visual-studio-code-4444db797954），but Report errors

` var doc = document, win = window, ArrayProto = Array.prototype, slice = ArrayProto.slice, filter = ArrayProto.filter, push = ArrayProto.push;
            ^
ReferenceError: document is not defined
    at /Users/smartcoach/grapesjs/node_modules/cash-dom/dist/cash.js:13:13
    at doc (/Users/smartcoach/grapesjs/node_modules/cash-dom/dist/cash.js:8:22)
    at Object.<anonymous> (/Users/smartcoach/grapesjs/node_modules/cash-dom/dist/cash.js:12:3)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
Waiting for the debugger to disconnect...`

I want to learn by debug ，please help.

**Comment by xr0master** [comment]
debug a client code for browser on server side? Just use a browser development mode.
