### ISSUE TITLE
Uncaught DOMException: Failed to execute 'matches' on 'Element': The provided selector is empty.

### ISSUE THREAD

**Issue by ajaykr089** [artf/grapesjs#2576]
Hi there,
I m getting below error while dropping components  on the canvas.
This only occurs if i have already some disabled components on the canvas.
`Uncaught DOMException: Failed to execute 'matches' on 'Element': The provided selector is empty.
    at r.matches (webpack-internal:///./node_modules/grapesjs/dist/grapes.min.js:12:222000)
    at r.validTarget (webpack-internal:///./node_modules/grapesjs/dist/grapes.min.js:12:226532)
    at r.dimsFromTarget (webpack-internal:///./node_modules/grapesjs/dist/grapes.min.js:12:227021)
    at r.onMove (webpack-internal:///./node_modules/grapesjs/dist/grapes.min.js:12:224501)
    at I (webpack-internal:///./node_modules/grapesjs/dist/grapes.min.js:2:8823)
    at HTMLBodyElement.eval (webpack-internal:///./node_modules/grapesjs/dist/grapes.min.js:2:9025)
    at HTMLBodyElement.eval (webpack-internal:///./node_modules/grapesjs/dist/grapes.min.js:2:2169)`

`grapes.min.js?a826:12 Uncaught TypeError: Cannot read property 'indexEl' of undefined
    at r.move (grapes.min.js?a826:12)
    at eval (grapes.min.js?a826:12)
    at Array.forEach (<anonymous>)
    at r.endMove (grapes.min.js?a826:12)
    at I (grapes.min.js?a826:2)
    at r.eval (grapes.min.js?a826:2)
    at r.eval [as endMove] (grapes.min.js?a826:2)
    at i (grapes.min.js?a826:12)
    at t.value (grapes.min.js?a826:12)
    at t.value (grapes.min.js?a826:12)`

Hope this helps to debug. 

any suggestion to handle above exception would be really helpfull.

Thanks in advance.

**Comment by artf** [comment]
Follow the issue template if you're submitting a BUG
