### ISSUE TITLE
BUG: Problem importing CSS and module in nodejs es6

### ISSUE THREAD

**Issue by moreorem** [artf/grapesjs#3045]
**Version:**
0.16.22

**Are you able to reproduce the bug from the demo?**

[x] Yes
[ ] No

**What is the expected behavior?**
To import grapejs css and module

*Describe the bug **detailed***

SyntaxError: Invalid or unexpected token
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10) 

AND

/project/node_modules/grapesjs/dist/grapes.min.js:1
ReferenceError: window is not defined
    at Object.<anonymous> (/home/orestes/Workspace/orbitplum/node_modules/grapesjs/dist/grapes.min.js:2:198)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/home/orestes/Workspace/orbitplum/test.js:1)
    at Generator.next (<anonymous>)

**Comment by artf** [comment]
sorry, are you able to provide a live example?
