### ISSUE TITLE
BUG: Running in headless mode requires window

### ISSUE THREAD

**Issue by bimsina** [artf/grapesjs#4474]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 103.0.5060.134

### Reproducible demo link

https://stackblitz.com/edit/node-zrdtg4?file=index.js

### Describe the bug

**How to reproduce the bug?**
1. Initialize Editor in headless mode
2. Load the project data with just a basic text node
<details>
  <summary>Click to expand for sample data.</summary>
  
  ```javascript
 const _justTextData = {
        assets: [],
        styles: [],
        pages: [
          {
            frames: [
              {
                component: {
                  type: 'wrapper',
                  stylable: [
                    'background',
                    'background-color',
                    'background-image',
                    'background-repeat',
                    'background-attachment',
                    'background-position',
                    'background-size',
                  ],
                  attributes: { id: 'ipfo' },
                  components: [
                    {
                      type: 'text',
                      attributes: { id: 'i1je' },
                      components: [{ type: 'textnode', content: 'Hello world!' }],
                    },
                  ],
                },
              },
            ],
            id: '7bbomSfhvWF8QvfD',
          },
        ],
};
  ```
</details>

Sample Code 
```
try {
  const editor = grapesjs.init({ headless: true });

  editor.loadProjectData(_justTextData);
  const html = editor.getHtml();
  const css = editor.getCss();

  console.log('html:', html);
  console.log('css:', css);
} catch (e) {
  console.log('error', e);
}
```

3. Generate the HTML and CSS using `editor.getHtml()` and `editor.getCss()` respectively.
4. HTML and CSS should be generated successfully.
5. Now Load the project with data containing text and image
<details>
  <summary>Click to expand for sample data.</summary>
  
  ```javascript
const _textWithImageData = {
  assets: [
    {
      type: 'image',
      src: 'https://images.unsplash.com/photo-1658397966058-d1d252892754?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80',
      unitDim: 'px',
      height: 0,
      width: 0,
    },
  ],
  styles: [
    {
      selectors: ['#ifvh'],
      style: { color: 'black' },
      mediaText: '(max-width: 900px)',
      atRuleType: 'media',
    },
  ],
  pages: [
    {
      frames: [
        {
          component: {
            type: 'wrapper',
            stylable: [
              'background',
              'background-color',
              'background-image',
              'background-repeat',
              'background-attachment',
              'background-position',
              'background-size',
            ],
            attributes: { id: 'ih1q' },
            components: [
              {
                type: 'text',
                attributes: { id: 'i29t' },
                components: [{ type: 'textnode', content: 'Hello World' }],
              },
              {
                type: 'image',
                attributes: {
                  id: 'ifvh',
                  src: 'https://images.unsplash.com/photo-1658397966058-d1d252892754?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80',
                },
              },
            ],
          },
        },
      ],
      id: '9T0c4L1n3IPynJMc',
    },
  ],
};
  ```
</details>
6. Generate HTML and CSS

-----

**What is the expected behavior?**
From what I understand, running on headless mode should not require window or document access, so HTML and CSS should in theory be generated in both cases.

**What is the current behavior?**
HTML and CSS is generated in the first case but not in the second case and throws an error.

```
error ReferenceError: window is not defined
    at U (/home/projects/node-zrdtg4/node_modules/grapesjs/dist/grapes.min.js:2:893064)
    at N.r.initialize (/home/projects/node-zrdtg4/node_modules/grapesjs/dist/grapes.min.js:2:794563)
    at new e.Model (/home/projects/node-zrdtg4/node_modules/grapesjs/dist/grapes.min.js:2:10599)
    at N.r.eval (/home/projects/node-zrdtg4/node_modules/grapesjs/dist/grapes.min.js:2:455301)
    at new n (/home/projects/node-zrdtg4/node_modules/grapesjs/dist/grapes.min.js:2:455545)
    at N.r.eval (/home/projects/node-zrdtg4/node_modules/grapesjs/dist/grapes.min.js:2:408184)
    at N.r.n (/home/projects/node-zrdtg4/node_modules/grapesjs/dist/grapes.min.js:2:408590)
    at new N.r (/home/projects/node-zrdtg4/node_modules/grapesjs/dist/grapes.min.js:2:28357)
    at new value (/home/projects/node-zrdtg4/node_modules/grapesjs/dist/grapes.min.js:2:440096)
    at n._prepareModel (/home/projects/node-zrdtg4/node_modules/grapesjs/dist/grapes.min.js:2:18706)
```

Same is the case when adding a video block, but only in this case the error is that `document is not defined
`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by skru** [comment]
see #4473

**Comment by artf** [comment]
Fixed here https://github.com/artf/grapesjs/commit/f61222ec904ed56794f7b97e362ea2006dfceaf6
