### ISSUE TITLE
traits sometime does not fire event

### ISSUE THREAD

**Issue by krunal039** [artf/grapesjs#629]
sometime traits change event does not fire event on model and view and I have seen below error for that.

Uncaught RangeError: Maximum call stack size exceeded.
at HTMLDivElement.<anonymous> (grapes.min.js:9229)
    at o (grapes.min.js:8871)
    at i.each (grapes.min.js:9131)
    at i.trigger (grapes.min.js:9228)
    at i.o.trigger (grapes.min.js:23251)
    at i.o.click (grapes.min.js:23274)
    at F.i.openSettings (grapesjs-hsbc.js:1232)
    at HTMLDivElement.<anonymous> (grapes.min.js:9229)
    at o (grapes.min.js:8871)
    at i.each (grapes.min.js:9131)

**Comment by artf** [comment]
@krunal039 about what event are you talking about? Can you provide at least an example of how I can reproduce it

**Comment by krunal039** [comment]
@artf below is codepen link and i have added custom component named slider. here when you drop slider to editor and than click on it and it should open trait manager and if you change Link Title or Link to Open to blank value it throws above error.

https://codepen.io/kmpdev/full/LORdOM/

error:

Uncaught RangeError: Maximum call stack size exceeded.
2grapes.min.js:2 Uncaught RangeError: Maximum call stack size exceeded.
    at HTMLDivElement.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.12.25/grapes.min.js:2:232013)
    at o (https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.12.25/grapes.min.js:2:225570)
    at i.each (https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.12.25/grapes.min.js:2:230006)
    at i.trigger (https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.12.25/grapes.min.js:2:231987)
    at i.o.trigger (https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.12.25/grapes.min.js:11:29611)
    at i.o.click (https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.12.25/grapes.min.js:11:30120)
    at i.openSettings (pen.js:1921:20)
    at HTMLDivElement.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.12.25/grapes.min.js:2:232013)
    at o (https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.12.25/grapes.min.js:2:225570)
    at i.each (https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.12.25/grapes.min.js:2:230006)

**Comment by artf** [comment]
I can't reproduce any error, but what I see wrong at the first look is how you update models
```js
...
someModel.attributes.href = this.get("a_href");
// use
someModel.set('href', this.get("a_href"));
```
then you don't need `$(this.el)`, you have already `this.$el`

**Comment by krunal039** [comment]
@artf I have updated a you suggested but still I can see error on console and also it does not trigger trait change event for "Link Title" and "Link to open" when value is empty.

below is error.

grapes.min.js:2 Uncaught RangeError: Maximum call stack size exceeded.
    at HTMLDivElement.<anonymous> (grapes.min.js:2)
    at o (grapes.min.js:2)
    at i.each (grapes.min.js:2)
    at i.trigger (grapes.min.js:2)
    at i.o.trigger (grapes.min.js:11)
    at i.o.click (grapes.min.js:11)
    at i.openSettings (pen.js:386)
    at HTMLDivElement.<anonymous> (grapes.min.js:2)
    at o (grapes.min.js:2)
    at i.each (grapes.min.js:2)

**Comment by artf** [comment]
@krunal039 first of all, update grapesjs to the latest version. 
You don't need jquery anymore, but if you still want to use its common APIs GrapesJS includes internally `cash`,  so you can use it like this
```js
const $ = grapesjs.$;
$(...)
```
BTW how do you listen to trait changes??
